import './globals.css'
import Footer from "../components/Footer/Footer";

export const metadata = {
  title: 'AirBnB',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
